### ISSUE TITLE
tooltips unreliable

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#92] opened 2016-11-06 06:56 UTC
@merryman 

Tooltip invocation is very unreliable.

Allt buttons in the browser below have a tooltip attribute.

Note that when hovering over the first button nothing happens.
Tooltip over the second appears but quite late.
Tooltip over the third appears immediately but also goes away while mouse is still over button and does not reappear when hovering over the button again.

![tooltip-bug](https://cloud.githubusercontent.com/assets/467450/20035883/7a742962-a3b3-11e6-82b0-730b04074c01.gif)

**Comment by merryman** [comment] 2016-11-06 10:56
I will look into this, however I could not really reproduce this bug. Can you push the version of the browser with the buttons so that I can take a look at that?

I will also add some tests for the tooltips. The bug is probably because currently the timeouts are closely coupled to the internal model of the tooltips.

**Comment by merryman** [comment] 2016-11-06 14:11
Ok, this was a problem when the tooltipped morph had submorphs that themselves did not carry tooltips, such as the labels in the case of the buttons here.
Fixed in: ba0a48d8be642cc064ccf9950de6e33b44ca3322

**Closed as completed by merryman** 2016-11-06 14:11 UTC

**Comment by rksm** [comment] 2016-11-07 03:43
👍
